# Generated by Django 2.2.5 on 2019-09-21 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190919_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=200, verbose_name='Почта')),
                ('adress', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Пост')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'описание', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Обсуждение', 'verbose_name_plural': 'Форум'},
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='Абзац'),
        ),
    ]
