# Generated by Django 2.2.5 on 2019-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20191001_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цытата')),
                ('link', models.CharField(max_length=200, verbose_name='Книга/глава/стих')),
            ],
            options={
                'verbose_name_plural': 'Библия',
                'verbose_name': 'цитату',
            },
        ),
    ]
