# Generated by Django 2.2.5 on 2019-10-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_bible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bible',
            options={'verbose_name': 'цитата', 'verbose_name_plural': 'Библия'},
        ),
    ]
