# Generated by Django 2.2.5 on 2019-10-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20191001_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
